name: gtcs_chat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4  # Add FCM for notifications
  flutter_local_notifications: ^19.0.0  # Add local notifications
  lottie: ^2.7.0
  provider: ^6.1.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/animation.json
    - assets/icon.png